var searchData=
[
  ['jamesnk_20newtonsoft_20json_20master_20doc_20icons_20logo_20jpg_20alt_20logo_20json_20net_0',['&lt;img src=&quot;https://raw.githubusercontent.com/JamesNK/Newtonsoft.Json/master/Doc/icons/logo.jpg&quot; alt=&quot;Logo&quot;/&gt; Json.NET',['../md_packages_2_newtonsoft_8_json_813_80_83_2_r_e_a_d_m_e.html',1,'']]],
  ['january_2031_202021_1',['NUnit 3.13.1 - January 31, 2021',['../md_packages_2_n_unit_83_813_81_2_c_h_a_n_g_e_s.html',1,'']]],
  ['join_20the_20chat_20at_20https_3a_20gitter_20im_20serilog_20serilog_20a_20a_20href_20http_3a_20stackoverflow_20com_20questions_20tagged_20serilog_20img_20src_20https_3a_20img_20shields_20io_20badge_20stackoverflow_20serilog_20orange_20svg_20alt_20help_20a_2',['Serilog.Sinks.Console &lt;a href=&quot;https://ci.appveyor.com/project/serilog/serilog-sinks-console/branch/master&quot; &gt;&lt;img src=&quot;https://ci.appveyor.com/api/projects/status/w1w3m1wyk3in1c96/branch/master?svg=true&quot; alt=&quot;Build status&quot;/&gt;&lt;/a&gt; &lt;a href=&quot;https://www.nuget.org/packages/Serilog.Sinks.Console/&quot; &gt;&lt;img src=&quot;http://img.shields.io/nuget/v/Serilog.Sinks.Console.svg?style=flat&quot; alt=&quot;NuGet Version&quot;/&gt;&lt;/a&gt; &lt;a href=&quot;https://github.com/serilog/serilog/wiki&quot; &gt;&lt;img src=&quot;https://img.shields.io/badge/docs-wiki-yellow.svg&quot; alt=&quot;Documentation&quot;/&gt;&lt;/a&gt; &lt;a href=&quot;https://gitter.im/serilog/serilog&quot; &gt;&lt;img src=&quot;https://img.shields.io/gitter/room/serilog/serilog.svg&quot; alt=&quot;Join the chat at https://gitter.im/serilog/serilog&quot;/&gt;&lt;/a&gt; &lt;a href=&quot;http://stackoverflow.com/questions/tagged/serilog&quot; &gt;&lt;img src=&quot;https://img.shields.io/badge/stackoverflow-serilog-orange.svg&quot; alt=&quot;Help&quot;/&gt;&lt;/a&gt;',['../md_packages_2_serilog_8_sinks_8_console_85_80_81_2_r_e_a_d_m_e.html',1,'']]],
  ['jpg_20alt_20logo_20json_20net_3',['&lt;img src=&quot;https://raw.githubusercontent.com/JamesNK/Newtonsoft.Json/master/Doc/icons/logo.jpg&quot; alt=&quot;Logo&quot;/&gt; Json.NET',['../md_packages_2_newtonsoft_8_json_813_80_83_2_r_e_a_d_m_e.html',1,'']]],
  ['json_20license_20mit_4',['Json LICENSE MIT',['../md_packages_2_spec_flow_83_89_874_2_licenses_2_newtonsoft_8_json-_l_i_c_e_n_s_e-_m_i_t.html',1,'Newtonsoft.Json-LICENSE-MIT'],['../md_packages_2_spec_flow_8_tools_8_ms_build_8_generation_83_89_874_2licenses_2_newtonsoft_8_json-_l_i_c_e_n_s_e-_m_i_t.html',1,'Newtonsoft.Json-LICENSE-MIT']]],
  ['json_20master_20doc_20icons_20logo_20jpg_20alt_20logo_20json_20net_5',['&lt;img src=&quot;https://raw.githubusercontent.com/JamesNK/Newtonsoft.Json/master/Doc/icons/logo.jpg&quot; alt=&quot;Logo&quot;/&gt; Json.NET',['../md_packages_2_newtonsoft_8_json_813_80_83_2_r_e_a_d_m_e.html',1,'']]]
];
